/* Autogenerated: ./src/ExtractionOCaml/word_by_word_montgomery pasta_fq 64 '2^254 + 45560315531506369815346746415080538113' */
/* curve description: pasta_fq */
/* machine_wordsize = 64 (from "64") */
/* requested operations: (all) */
/* m = 0x40000000000000000000000000000000224698fc0994a8dd8c46eb2100000001 (from "2^254 + 45560315531506369815346746415080538113") */
/*                                                                    */
/* NOTE: In addition to the bounds specified above each function, all */
/*   functions synthesized for this Montgomery arithmetic require the */
/*   input to be strictly less than the prime modulus (m), and also   */
/*   require the input to be in the unique saturated representation.  */
/*   All functions also ensure that these two properties are true of  */
/*   return values.                                                   */
/*  */
/* Computed values: */
/* eval z = z[0] + (z[1] << 64) + (z[2] << 128) + (z[3] << 192) */
/* bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) + (z[17] << 136) + (z[18] << 144) + (z[19] << 152) + (z[20] << 160) + (z[21] << 168) + (z[22] << 176) + (z[23] << 184) + (z[24] << 192) + (z[25] << 200) + (z[26] << 208) + (z[27] << 216) + (z[28] << 224) + (z[29] << 232) + (z[30] << 240) + (z[31] << 248) */

#include <stdint.h>
#include <inttypes.h>

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif

#include "pasta.h"

/*
 * The function fiat_pasta_fq_set_one returns the field element one in the Montgomery domain.
 * Postconditions:
 *   eval (from_montgomery out1) mod m = 1 mod m
 *   0 ≤ eval out1 < m
 *
 * Input Bounds:
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 */
void fiat_pasta_fq_set_one(uint64_t out1[4]) {
  out1[0] = UINT64_C(0x5b2b3e9cfffffffd);
  out1[1] = UINT64_C(0x992c350be3420567);
  out1[2] = UINT64_C(0xffffffffffffffff);
  out1[3] = UINT64_C(0x3fffffffffffffff);
}

/*
 * The function fiat_pasta_fq_divstep_precomp returns the precomputed value for Bernstein-Yang-inversion (in montgomery form).
 * Postconditions:
 *   eval (from_montgomery out1) = ⌊(m - 1) / 2⌋^(if (log2 m) + 1 < 46 then ⌊(49 * ((log2 m) + 1) + 80) / 17⌋ else ⌊(49 * ((log2 m) + 1) + 57) / 17⌋)
 *   0 ≤ eval out1 < m
 *
 * Input Bounds:
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 */
void fiat_pasta_fq_divstep_precomp(uint64_t out1[4]) {
  out1[0] = UINT64_C(0xe6083b32dccd2992);
  out1[1] = UINT64_C(0x624453584f3bdab6);
  out1[2] = UINT64_C(0xba6367a9c5d2c08e);
  out1[3] = UINT64_C(0x1468dbacb19ab3af);
}

/*
 * The function fiat_pasta_fq_divstep computes a divstep.
 * Preconditions:
 *   0 ≤ eval arg4 < m
 *   0 ≤ eval arg5 < m
 * Postconditions:
 *   out1 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then 1 - arg1 else 1 + arg1)
 *   twos_complement_eval out2 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then twos_complement_eval arg3 else twos_complement_eval arg2)
 *   twos_complement_eval out3 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then ⌊(twos_complement_eval arg3 - twos_complement_eval arg2) / 2⌋ else ⌊(twos_complement_eval arg3 + (twos_complement_eval arg3 mod 2) * twos_complement_eval arg2) / 2⌋)
 *   eval (from_montgomery out4) mod m = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then (2 * eval (from_montgomery arg5)) mod m else (2 * eval (from_montgomery arg4)) mod m)
 *   eval (from_montgomery out5) mod m = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then (eval (from_montgomery arg4) - eval (from_montgomery arg4)) mod m else (eval (from_montgomery arg5) + (twos_complement_eval arg3 mod 2) * eval (from_montgomery arg4)) mod m)
 *   0 ≤ eval out5 < m
 *   0 ≤ eval out5 < m
 *   0 ≤ eval out2 < m
 *   0 ≤ eval out3 < m
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0xffffffffffffffff]
 *   arg2: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   arg3: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   arg4: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   arg5: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 *   out2: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   out3: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   out4: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   out5: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 */
void fiat_pasta_fq_divstep(uint64_t* out1, uint64_t out2[5], uint64_t out3[5], uint64_t out4[4], uint64_t out5[4], uint64_t arg1, const uint64_t arg2[5], const uint64_t arg3[5], const uint64_t arg4[4], const uint64_t arg5[4]) {
  uint64_t x1;
  fiat_pasta_uint1 x2;
  fiat_pasta_uint1 x3;
  uint64_t x4;
  fiat_pasta_uint1 x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  uint64_t x9;
  uint64_t x10;
  uint64_t x11;
  uint64_t x12;
  fiat_pasta_uint1 x13;
  uint64_t x14;
  fiat_pasta_uint1 x15;
  uint64_t x16;
  fiat_pasta_uint1 x17;
  uint64_t x18;
  fiat_pasta_uint1 x19;
  uint64_t x20;
  fiat_pasta_uint1 x21;
  uint64_t x22;
  uint64_t x23;
  uint64_t x24;
  uint64_t x25;
  uint64_t x26;
  uint64_t x27;
  uint64_t x28;
  uint64_t x29;
  uint64_t x30;
  uint64_t x31;
  fiat_pasta_uint1 x32;
  uint64_t x33;
  fiat_pasta_uint1 x34;
  uint64_t x35;
  fiat_pasta_uint1 x36;
  uint64_t x37;
  fiat_pasta_uint1 x38;
  uint64_t x39;
  fiat_pasta_uint1 x40;
  uint64_t x41;
  fiat_pasta_uint1 x42;
  uint64_t x43;
  fiat_pasta_uint1 x44;
  uint64_t x45;
  fiat_pasta_uint1 x46;
  uint64_t x47;
  fiat_pasta_uint1 x48;
  uint64_t x49;
  uint64_t x50;
  uint64_t x51;
  uint64_t x52;
  uint64_t x53;
  fiat_pasta_uint1 x54;
  uint64_t x55;
  fiat_pasta_uint1 x56;
  uint64_t x57;
  fiat_pasta_uint1 x58;
  uint64_t x59;
  fiat_pasta_uint1 x60;
  uint64_t x61;
  uint64_t x62;
  fiat_pasta_uint1 x63;
  uint64_t x64;
  fiat_pasta_uint1 x65;
  uint64_t x66;
  fiat_pasta_uint1 x67;
  uint64_t x68;
  fiat_pasta_uint1 x69;
  uint64_t x70;
  uint64_t x71;
  uint64_t x72;
  uint64_t x73;
  fiat_pasta_uint1 x74;
  uint64_t x75;
  uint64_t x76;
  uint64_t x77;
  uint64_t x78;
  uint64_t x79;
  uint64_t x80;
  fiat_pasta_uint1 x81;
  uint64_t x82;
  fiat_pasta_uint1 x83;
  uint64_t x84;
  fiat_pasta_uint1 x85;
  uint64_t x86;
  fiat_pasta_uint1 x87;
  uint64_t x88;
  fiat_pasta_uint1 x89;
  uint64_t x90;
  uint64_t x91;
  uint64_t x92;
  uint64_t x93;
  uint64_t x94;
  fiat_pasta_uint1 x95;
  uint64_t x96;
  fiat_pasta_uint1 x97;
  uint64_t x98;
  fiat_pasta_uint1 x99;
  uint64_t x100;
  fiat_pasta_uint1 x101;
  uint64_t x102;
  fiat_pasta_uint1 x103;
  uint64_t x104;
  fiat_pasta_uint1 x105;
  uint64_t x106;
  fiat_pasta_uint1 x107;
  uint64_t x108;
  fiat_pasta_uint1 x109;
  uint64_t x110;
  fiat_pasta_uint1 x111;
  uint64_t x112;
  fiat_pasta_uint1 x113;
  uint64_t x114;
  uint64_t x115;
  uint64_t x116;
  uint64_t x117;
  uint64_t x118;
  uint64_t x119;
  uint64_t x120;
  uint64_t x121;
  uint64_t x122;
  uint64_t x123;
  uint64_t x124;
  uint64_t x125;
  uint64_t x126;
  fiat_pasta_addcarryx_u64(&x1, &x2, 0x0, (~arg1), 0x1);
  x3 = (fiat_pasta_uint1)((fiat_pasta_uint1)(x1 >> 63) & (fiat_pasta_uint1)((arg3[0]) & 0x1));
  fiat_pasta_addcarryx_u64(&x4, &x5, 0x0, (~arg1), 0x1);
  fiat_pasta_cmovznz_u64(&x6, x3, arg1, x4);
  fiat_pasta_cmovznz_u64(&x7, x3, (arg2[0]), (arg3[0]));
  fiat_pasta_cmovznz_u64(&x8, x3, (arg2[1]), (arg3[1]));
  fiat_pasta_cmovznz_u64(&x9, x3, (arg2[2]), (arg3[2]));
  fiat_pasta_cmovznz_u64(&x10, x3, (arg2[3]), (arg3[3]));
  fiat_pasta_cmovznz_u64(&x11, x3, (arg2[4]), (arg3[4]));
  fiat_pasta_addcarryx_u64(&x12, &x13, 0x0, 0x1, (~(arg2[0])));
  fiat_pasta_addcarryx_u64(&x14, &x15, x13, 0x0, (~(arg2[1])));
  fiat_pasta_addcarryx_u64(&x16, &x17, x15, 0x0, (~(arg2[2])));
  fiat_pasta_addcarryx_u64(&x18, &x19, x17, 0x0, (~(arg2[3])));
  fiat_pasta_addcarryx_u64(&x20, &x21, x19, 0x0, (~(arg2[4])));
  fiat_pasta_cmovznz_u64(&x22, x3, (arg3[0]), x12);
  fiat_pasta_cmovznz_u64(&x23, x3, (arg3[1]), x14);
  fiat_pasta_cmovznz_u64(&x24, x3, (arg3[2]), x16);
  fiat_pasta_cmovznz_u64(&x25, x3, (arg3[3]), x18);
  fiat_pasta_cmovznz_u64(&x26, x3, (arg3[4]), x20);
  fiat_pasta_cmovznz_u64(&x27, x3, (arg4[0]), (arg5[0]));
  fiat_pasta_cmovznz_u64(&x28, x3, (arg4[1]), (arg5[1]));
  fiat_pasta_cmovznz_u64(&x29, x3, (arg4[2]), (arg5[2]));
  fiat_pasta_cmovznz_u64(&x30, x3, (arg4[3]), (arg5[3]));
  fiat_pasta_addcarryx_u64(&x31, &x32, 0x0, x27, x27);
  fiat_pasta_addcarryx_u64(&x33, &x34, x32, x28, x28);
  fiat_pasta_addcarryx_u64(&x35, &x36, x34, x29, x29);
  fiat_pasta_addcarryx_u64(&x37, &x38, x36, x30, x30);
  fiat_pasta_subborrowx_u64(&x39, &x40, 0x0, x31, UINT64_C(0x8c46eb2100000001));
  fiat_pasta_subborrowx_u64(&x41, &x42, x40, x33, UINT64_C(0x224698fc0994a8dd));
  fiat_pasta_subborrowx_u64(&x43, &x44, x42, x35, 0x0);
  fiat_pasta_subborrowx_u64(&x45, &x46, x44, x37, bb);
  fiat_pasta_subborrowx_u64(&x47, &x48, x46, x38, 0x0);
  x49 = (arg4[3]);
  x50 = (arg4[2]);
  x51 = (arg4[1]);
  x52 = (arg4[0]);
  fiat_pasta_subborrowx_u64(&x53, &x54, 0x0, 0x0, x52);
  fiat_pasta_subborrowx_u64(&x55, &x56, x54, 0x0, x51);
  fiat_pasta_subborrowx_u64(&x57, &x58, x56, 0x0, x50);
  fiat_pasta_subborrowx_u64(&x59, &x60, x58, 0x0, x49);
  fiat_pasta_cmovznz_u64(&x61, x60, 0x0, UINT64_C(0xffffffffffffffff));
  fiat_pasta_addcarryx_u64(&x62, &x63, 0x0, x53, (x61 & UINT64_C(0x8c46eb2100000001)));
  fiat_pasta_addcarryx_u64(&x64, &x65, x63, x55, (x61 & UINT64_C(0x224698fc0994a8dd)));
  fiat_pasta_addcarryx_u64(&x66, &x67, x65, x57, 0x0);
  fiat_pasta_addcarryx_u64(&x68, &x69, x67, x59, (x61 & bb));
  fiat_pasta_cmovznz_u64(&x70, x3, (arg5[0]), x62);
  fiat_pasta_cmovznz_u64(&x71, x3, (arg5[1]), x64);
  fiat_pasta_cmovznz_u64(&x72, x3, (arg5[2]), x66);
  fiat_pasta_cmovznz_u64(&x73, x3, (arg5[3]), x68);
  x74 = (fiat_pasta_uint1)(x22 & 0x1);
  fiat_pasta_cmovznz_u64(&x75, x74, 0x0, x7);
  fiat_pasta_cmovznz_u64(&x76, x74, 0x0, x8);
  fiat_pasta_cmovznz_u64(&x77, x74, 0x0, x9);
  fiat_pasta_cmovznz_u64(&x78, x74, 0x0, x10);
  fiat_pasta_cmovznz_u64(&x79, x74, 0x0, x11);
  fiat_pasta_addcarryx_u64(&x80, &x81, 0x0, x22, x75);
  fiat_pasta_addcarryx_u64(&x82, &x83, x81, x23, x76);
  fiat_pasta_addcarryx_u64(&x84, &x85, x83, x24, x77);
  fiat_pasta_addcarryx_u64(&x86, &x87, x85, x25, x78);
  fiat_pasta_addcarryx_u64(&x88, &x89, x87, x26, x79);
  fiat_pasta_cmovznz_u64(&x90, x74, 0x0, x27);
  fiat_pasta_cmovznz_u64(&x91, x74, 0x0, x28);
  fiat_pasta_cmovznz_u64(&x92, x74, 0x0, x29);
  fiat_pasta_cmovznz_u64(&x93, x74, 0x0, x30);
  fiat_pasta_addcarryx_u64(&x94, &x95, 0x0, x70, x90);
  fiat_pasta_addcarryx_u64(&x96, &x97, x95, x71, x91);
  fiat_pasta_addcarryx_u64(&x98, &x99, x97, x72, x92);
  fiat_pasta_addcarryx_u64(&x100, &x101, x99, x73, x93);
  fiat_pasta_subborrowx_u64(&x102, &x103, 0x0, x94, UINT64_C(0x8c46eb2100000001));
  fiat_pasta_subborrowx_u64(&x104, &x105, x103, x96, UINT64_C(0x224698fc0994a8dd));
  fiat_pasta_subborrowx_u64(&x106, &x107, x105, x98, 0x0);
  fiat_pasta_subborrowx_u64(&x108, &x109, x107, x100, bb);
  fiat_pasta_subborrowx_u64(&x110, &x111, x109, x101, 0x0);
  fiat_pasta_addcarryx_u64(&x112, &x113, 0x0, x6, 0x1);
  x114 = ((x80 >> 1) | ((x82 << 63) & UINT64_C(0xffffffffffffffff)));
  x115 = ((x82 >> 1) | ((x84 << 63) & UINT64_C(0xffffffffffffffff)));
  x116 = ((x84 >> 1) | ((x86 << 63) & UINT64_C(0xffffffffffffffff)));
  x117 = ((x86 >> 1) | ((x88 << 63) & UINT64_C(0xffffffffffffffff)));
  x118 = ((x88 & UINT64_C(0x8000000000000000)) | (x88 >> 1));
  fiat_pasta_cmovznz_u64(&x119, x48, x39, x31);
  fiat_pasta_cmovznz_u64(&x120, x48, x41, x33);
  fiat_pasta_cmovznz_u64(&x121, x48, x43, x35);
  fiat_pasta_cmovznz_u64(&x122, x48, x45, x37);
  fiat_pasta_cmovznz_u64(&x123, x111, x102, x94);
  fiat_pasta_cmovznz_u64(&x124, x111, x104, x96);
  fiat_pasta_cmovznz_u64(&x125, x111, x106, x98);
  fiat_pasta_cmovznz_u64(&x126, x111, x108, x100);
  *out1 = x112;
  out2[0] = x7;
  out2[1] = x8;
  out2[2] = x9;
  out2[3] = x10;
  out2[4] = x11;
  out3[0] = x114;
  out3[1] = x115;
  out3[2] = x116;
  out3[3] = x117;
  out3[4] = x118;
  out4[0] = x119;
  out4[1] = x120;
  out4[2] = x121;
  out4[3] = x122;
  out5[0] = x123;
  out5[1] = x124;
  out5[2] = x125;
  out5[3] = x126;
}
